# Generated by Django 3.1.7 on 2021-05-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlayInfo',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False)),
                ('play_name', models.CharField(blank=True, default='', max_length=20)),
                ('play_headcount', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('play_male_num', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('play_female_num', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('play_score', models.PositiveSmallIntegerField(blank=True, default=3)),
                ('play_intro', models.TextField(blank=True, default='')),
                ('play_img', models.CharField(blank=True, default='', max_length=50)),
                ('play_is_original', models.BooleanField(blank=True, default=False)),
                ('play_created', models.DateTimeField(auto_now_add=True)),
                ('play_duration', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ('play_created',),
            },
        ),
        migrations.CreateModel(
            name='TestStoreInfo',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, default='', max_length=20)),
                ('store_address', models.CharField(blank=True, default='', max_length=50)),
                ('store_contacts', models.CharField(blank=True, default='', max_length=10)),
                ('store_tel', models.CharField(blank=True, default='', max_length=15)),
                ('store_wechat', models.CharField(blank=True, default='', max_length=20)),
                ('store_pic', models.CharField(blank=True, default='', max_length=20)),
                ('store_created', models.DateTimeField(auto_now_add=True)),
                ('store_status', models.PositiveSmallIntegerField(default=0)),
                ('store_info', models.CharField(blank=True, default='', max_length=25)),
                ('store_deposit', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('store_created',),
            },
        ),
        migrations.CreateModel(
            name='TestUserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_openid', models.CharField(default='', max_length=32)),
                ('user_gender', models.PositiveSmallIntegerField(default=0)),
                ('user_nickName', models.CharField(default='', max_length=30)),
                ('user_avatarUrl', models.TextField(blank=True, default='')),
                ('user_province', models.CharField(blank=True, default='', max_length=16)),
                ('user_city', models.CharField(blank=True, default='', max_length=32)),
                ('user_phoneNum', models.CharField(blank=True, default='', max_length=15)),
                ('user_purePhoneNum', models.CharField(blank=True, default='', max_length=20)),
                ('user_countryCode', models.CharField(blank=True, default='', max_length=25)),
                ('user_lastLoginTime', models.DateTimeField()),
                ('user_lastLoginSysInfo', models.TextField(blank=True, default='')),
                ('user_lastLoginIp', models.CharField(blank=True, default='', max_length=16)),
                ('user_createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user_createTime',),
            },
        ),
        migrations.CreateModel(
            name='TestStorePlayRepoInfo',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_price', models.PositiveSmallIntegerField(default=0)),
                ('item_create_time', models.DateTimeField(auto_now_add=True)),
                ('play_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_stores', to='pzz_for_test.testplayinfo')),
                ('store_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_plays', to='pzz_for_test.teststoreinfo')),
            ],
            options={
                'ordering': ('item_create_time',),
            },
        ),
        migrations.CreateModel(
            name='TestQueueInfo',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_status', models.SmallIntegerField(default=0)),
                ('queue_create_time', models.DateTimeField(auto_now_add=True)),
                ('queue_end_time', models.DateTimeField()),
                ('queue_current_num', models.SmallIntegerField(default=0)),
                ('queue_current_male_num', models.SmallIntegerField(default=0)),
                ('queue_current_female_num', models.SmallIntegerField(default=0)),
                ('queue_allow_antigender', models.BooleanField(default=False)),
                ('play_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='all_queues', to='pzz_for_test.testplayinfo')),
                ('store_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='all_queues', to='pzz_for_test.teststoreinfo')),
            ],
            options={
                'ordering': ('queue_create_time',),
            },
        ),
        migrations.CreateModel(
            name='TestPlayerInfo',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(default='', max_length=10)),
                ('player_gender', models.PositiveSmallIntegerField(default=0)),
                ('player_pic', models.CharField(blank=True, default='', max_length=20)),
                ('player_wechat', models.CharField(blank=True, default='', max_length=20)),
                ('player_tel', models.CharField(blank=True, default='', max_length=16)),
                ('player_time', models.DateTimeField(auto_now_add=True)),
                ('queue_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_players', to='pzz_for_test.testqueueinfo')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='all_players', to='pzz_for_test.testuserinfo')),
            ],
            options={
                'ordering': ('player_time',),
            },
        ),
        migrations.CreateModel(
            name='TestLabelInfo',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_type', models.PositiveSmallIntegerField(default=0)),
                ('label_content', models.CharField(default='', max_length=5)),
                ('label_create_time', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_labels', to='pzz_for_test.teststoreplayrepoinfo')),
                ('play_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_labels', to='pzz_for_test.testplayinfo')),
            ],
            options={
                'ordering': ('label_create_time',),
            },
        ),
    ]
