# Generated by Django 3.1.7 on 2021-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuserinfo',
            name='user_lastModifiedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testuserinfo',
            name='user_lastSessionKey',
            field=models.CharField(default='', max_length=32),
        ),
    ]
