# Generated by Django 3.1.7 on 2021-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststoreinfo',
            name='store_pic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teststoreinfo',
            name='store_tel',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
