# Generated by Django 3.1.7 on 2021-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0002_auto_20210501_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuserinfo',
            name='user_last3rdSession',
            field=models.CharField(default='', max_length=32),
        ),
    ]
