# Generated by Django 3.1.7 on 2021-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0003_testuserinfo_user_last3rdsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplayerinfo',
            name='player_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
