# Generated by Django 3.1.7 on 2021-04-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0004_auto_20210407_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlayerInfo',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(default='', max_length=10)),
                ('player_gender', models.PositiveSmallIntegerField(default=0)),
                ('player_pic', models.CharField(blank=True, default='', max_length=20)),
                ('player_wechat', models.CharField(blank=True, default='', max_length=20)),
                ('player_time', models.DateTimeField(auto_now_add=True)),
                ('queue_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='all_players', to='pzz_for_test.testqueueinfo')),
            ],
            options={
                'ordering': ('player_time',),
            },
        ),
    ]
