# Generated by Django 3.1.7 on 2021-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0004_testplayerinfo_player_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplayerinfo',
            name='player_pic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
