# Generated by Django 3.1.7 on 2021-05-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0005_auto_20210503_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAdminInfo',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_openid', models.CharField(default='', max_length=32)),
                ('admin_gender', models.PositiveSmallIntegerField(default=0)),
                ('admin_nickName', models.CharField(default='', max_length=30)),
                ('admin_avatarUrl', models.TextField(blank=True, default='')),
                ('admin_province', models.CharField(blank=True, default='', max_length=16)),
                ('admin_city', models.CharField(blank=True, default='', max_length=32)),
                ('admin_phoneNum', models.CharField(blank=True, default='', max_length=15)),
                ('admin_purePhoneNum', models.CharField(blank=True, default='', max_length=20)),
                ('admin_countryCode', models.CharField(blank=True, default='', max_length=25)),
                ('admin_lastLoginTime', models.DateTimeField()),
                ('admin_lastLoginSysInfo', models.TextField(blank=True, default='')),
                ('admin_lastLoginIp', models.CharField(blank=True, default='', max_length=16)),
                ('admin_lastModifiedTime', models.DateTimeField(auto_now=True)),
                ('admin_lastSessionKey', models.CharField(default='', max_length=32)),
                ('admin_last3rdSession', models.CharField(default='', max_length=32)),
                ('admin_createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('admin_createTime',),
            },
        ),
        migrations.CreateModel(
            name='TestAdminStoreInfo',
            fields=[
                ('adminStore_id', models.AutoField(primary_key=True, serialize=False)),
                ('adminStore_permission', models.SmallIntegerField(default=0)),
                ('adminStore_createTime', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_adminStores', to='pzz_for_test.testadmininfo')),
                ('store_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_admins', to='pzz_for_test.teststoreinfo')),
            ],
            options={
                'ordering': ('adminStore_createTime',),
            },
        ),
    ]
