# Generated by Django 3.1.7 on 2021-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0005_testplayerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststoreinfo',
            name='store_deposit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
