# Generated by Django 3.1.7 on 2021-04-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0006_teststoreinfo_store_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplayerinfo',
            name='player_tel',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
