# Generated by Django 3.1.7 on 2021-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0006_testadmininfo_testadminstoreinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testadminstoreinfo',
            name='adminStore_idCard',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='testadminstoreinfo',
            name='adminStore_name',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='testadminstoreinfo',
            name='adminStore_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
