# Generated by Django 3.1.7 on 2021-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0007_testplayerinfo_player_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststoreinfo',
            name='store_info',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
