# Generated by Django 3.1.7 on 2021-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0007_auto_20210513_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststoreinfo',
            name='store_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teststoreinfo',
            name='store_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teststoreinfo',
            name='store_position',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teststoreinfo',
            name='store_tel2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='testplayinfo',
            name='play_img',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teststoreinfo',
            name='store_pic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
