# Generated by Django 3.1.7 on 2021-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0008_auto_20210423_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplayinfo',
            name='play_img',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
