# Generated by Django 3.1.7 on 2021-05-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0009_testplayinfo_play_antigender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlabelinfo',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_labels', to='pzz_for_test.teststoreplayrepoinfo'),
        ),
        migrations.AlterField(
            model_name='testlabelinfo',
            name='play_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_labels', to='pzz_for_test.testplayinfo'),
        ),
        migrations.AlterField(
            model_name='teststoreplayrepoinfo',
            name='play_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_stores', to='pzz_for_test.testplayinfo'),
        ),
        migrations.AlterField(
            model_name='teststoreplayrepoinfo',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_plays', to='pzz_for_test.teststoreinfo'),
        ),
    ]
