# Generated by Django 3.1.7 on 2021-04-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0009_auto_20210423_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStorePlayRepoInfo',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_price', models.PositiveSmallIntegerField(default=0)),
                ('item_create_time', models.DateTimeField(auto_now_add=True)),
                ('play_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='all_stores', to='pzz_for_test.testplayinfo')),
                ('store_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='all_plays', to='pzz_for_test.teststoreinfo')),
            ],
            options={
                'ordering': ('item_create_time',),
            },
        ),
    ]
