# Generated by Django 3.1.7 on 2021-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0011_auto_20210521_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='testadminstoreinfo',
            name='adminStore_verify',
            field=models.SmallIntegerField(default=0),
        ),
    ]
