# Generated by Django 3.1.7 on 2021-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz_for_test', '0013_auto_20210523_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testadminstoreinfo',
            name='adminStore_verify',
            field=models.SmallIntegerField(default=0),
        ),
    ]
